### ISSUE TITLE
Create factory for http request building

### ISSUE THREAD

**Issue by xrem** [fbashilov/EXT-api#1]
According to DRY principle of software development, I would recommend to replace all places where HTTP request is performed by calling some factory function that will same return promise.

https://github.com/fbashilov/EXT-api/blob/a89271eafc34a8502d6423957a9e74a8ab8a1407/code-identityserver-sample.js#L354-L378
https://github.com/fbashilov/EXT-api/blob/a89271eafc34a8502d6423957a9e74a8ab8a1407/s2s.js#L139-L160

i.e. we can make function with signature like this `makeRequest(method, url, body)`.
AccessToken is shared among all requests, so headers can be encapsulated inside.

Also, it would be nice to have a bit more modern HTTP request processing through [fetch()](https://learn.javascript.ru/fetch#post-zaprosy)

**Comment by fbashilov** [comment]
Created makeRequest factory with fetch method
