### ISSUE TITLE
Misspelled words

### ISSUE THREAD

**Issue by xrem** [fbashilov/EXT-api#2]
For me, it looks like I would not receive a token if there are any scopes specified, because the parameter is misspelled.
https://github.com/fbashilov/EXT-api/blob/a89271eafc34a8502d6423957a9e74a8ab8a1407/s2s.js#L41

**Comment by xrem** [comment]
And another one:
https://github.com/fbashilov/EXT-api/blob/a89271eafc34a8502d6423957a9e74a8ab8a1407/code-identityserver-sample.js#L347

**Comment by fbashilov** [comment]
Fixed
